"""Known access patterns: edge proxies in front of an origin, mesh VPNs for admin access, and
tunnels that need no inbound port at all.

Edge ranges come from each provider's published list (see provider_ranges.py, regenerated by
scripts/update_provider_ranges.py, each list dated). A firewall source is attributed to a
provider only when it lies entirely inside that provider's ranges.
"""

from __future__ import annotations

import ipaddress
from typing import Any

from .provider_ranges import EDGE_RANGES

Network = ipaddress.IPv4Network | ipaddress.IPv6Network

EDGE_NETWORKS: dict[str, tuple[Network, ...]] = {
    key: tuple(ipaddress.ip_network(value) for value in entry["ranges"]) for key, entry in EDGE_RANGES.items()
}
EDGE_NAMES = {key: str(entry["name"]) for key, entry in EDGE_RANGES.items()}
# Providers that publish no complete list: recognized by name in docs, never guessed from IPs.
UNVERIFIABLE_EDGE = {"akamai": "Akamai", "sucuri": "Sucuri"}

# Tailscale, Headscale, and NetBird all hand out addresses from the CGNAT range by default.
MESH_RANGES: tuple[Network, ...] = (ipaddress.ip_network("100.64.0.0/10"), ipaddress.ip_network("fd7a:115c:a1e0::/48"))
MESH_NAME = "Mesh VPN (Tailscale, Headscale, NetBird)"
# UDP ports a world-open rule needs so mesh peers can connect directly; not a service exposure.
MESH_UDP_PORTS = {41641: "Tailscale", 51820: "WireGuard / NetBird", 9993: "ZeroTier"}
MESH_INTERFACES = ("tailscale", "wt", "wg", "zt")
# Agents that publish a service through an outbound connection, so no inbound port is needed.
TUNNEL_AGENTS = {
    "cloudflared": "Cloudflare Tunnel",
    "ngrok": "ngrok",
    "tailscaled": "Tailscale (Serve/Funnel possible)",
    "netbird": "NetBird",
    "zerotier-one": "ZeroTier",
    "frpc": "frp",
}


def _network(source: str) -> Network | None:
    try:
        return ipaddress.ip_network(source, strict=False)
    except ValueError:
        return None


def _inside(network: Network, ranges: tuple[Network, ...]) -> bool:
    return any(network.version == candidate.version and network.subnet_of(candidate) for candidate in ranges)  # type: ignore[arg-type]


def edge_provider(source: str) -> str | None:
    """Name of the edge provider whose published ranges contain ``source``, if any."""
    network = _network(source)
    if network is None or network.prefixlen == 0:
        return None
    for key, ranges in EDGE_NETWORKS.items():
        if _inside(network, ranges):
            return EDGE_NAMES[key]
    return None


def is_mesh(source: str) -> bool:
    network = _network(source)
    return network is not None and _inside(network, MESH_RANGES)


def mesh_port(protocol: object, port: object) -> str | None:
    """The mesh VPN a world-open UDP port belongs to, if it is a known one."""
    return MESH_UDP_PORTS.get(port) if protocol == "udp" and isinstance(port, int) else None


def tunnel_agents(props: dict[str, Any]) -> list[str]:
    """Tunnel agents seen in host evidence: running processes, listener processes, or container images."""
    seen: set[str] = set()
    names = [str(item) for item in props.get("host_agents") or []]
    names += [str(item.get("process") or "") for item in props.get("listeners") or []]
    for name in names:
        if name in TUNNEL_AGENTS:
            seen.add(TUNNEL_AGENTS[name])
    return sorted(seen)


def container_tunnels(images: list[str]) -> list[str]:
    seen = set()
    for image in images:
        lowered = image.lower()
        for agent, label in TUNNEL_AGENTS.items():
            if agent in lowered:
                seen.add(label)
    return sorted(seen)


def edge_ranges_as_of(provider_name: str) -> str | None:
    return next((str(entry["as_of"]) for entry in EDGE_RANGES.values() if entry["name"] == provider_name), None)
