"""Network topology map: who can send traffic where, rendered as Mermaid, SVG, or JSON.

The map is built only from normalized provider evidence (servers, networks, firewall rules).
Public IP addresses are never rendered; sources are summarized by trust class.
"""

from __future__ import annotations

import ipaddress
from html import escape
from typing import Any

from .flows import port_set
from .models import Asset, Snapshot
from .provider_ranges import EDGE_RANGES
from .providers import (
    EDGE_NETWORKS,
    MESH_RANGES,
    container_tunnels,
    edge_provider,
    is_mesh,
    mesh_port,
    tunnel_agents,
)
from .text import md

# Edge ranges come from providers.py (dated, regenerated by scripts/update_provider_ranges.py).
CLOUDFLARE_RANGES_AS_OF = str(EDGE_RANGES["cloudflare"]["as_of"])
CLOUDFLARE_RANGES = EDGE_NETWORKS["cloudflare"]
TAILSCALE_RANGES = MESH_RANGES
WORLD = {"0.0.0.0/0", "::/0"}
SENSITIVE_PORTS = {22, 2375, 2376, 3306, 5432, 6379, 6443, 9200, 27017}

SOURCE_LABELS = {
    "world": "Internet (any address)",
    "edge": "Edge proxy / CDN only",
    "mesh": "Mesh VPN (Tailscale, Headscale, NetBird)",
    "private": "Private network",
    "allowlist": "Allow-listed addresses",
}

GROUPS = (
    ("edge", "Edge & web", ("edge", "fe", "web", "proxy", "lb", "gateway")),
    ("security", "Identity & secrets", ("vault", "auth", "identity", "secret", "kms")),
    ("data", "Data", ("db", "database", "postgres", "redis", "replica", "warehouse", "data", "storage")),
    ("app", "Applications", ("app", "api", "worker", "service", "bus", "agent")),
)


def _within(source: str, ranges: tuple[Any, ...]) -> bool:
    try:
        network = ipaddress.ip_network(source, strict=False)
    except ValueError:
        return False
    return any(
        network.version == candidate.version and network.subnet_of(candidate)
        for candidate in ranges
    )


def classify_source(source: str, private_ranges: tuple[Any, ...]) -> str:
    if source in WORLD:
        return "world"
    if edge_provider(source):
        return "edge"
    if is_mesh(source):
        return "mesh"
    if private_ranges and _within(source, private_ranges):
        return "private"
    return "allowlist"


def _port_text(rule: dict[str, Any]) -> str:
    protocol = str(rule.get("protocol", "tcp"))
    if protocol in {"icmp", "esp", "gre"}:
        return protocol
    start, end = rule.get("port_from"), rule.get("port_to")
    if start is None:
        return f"{protocol}/all"
    return f"{protocol}/{start}" if start == end else f"{protocol}/{start}-{end}"


def _port_sort_key(port: str) -> tuple[int, str]:
    digits = "".join(char for char in port.split("/")[-1].split("-")[0] if char.isdigit())
    return (int(digits) if digits else 1 << 20, port)


def _group(server: Asset) -> str:
    text = " ".join(
        [server.labels.get("role", ""), server.labels.get("service", ""), server.name]
    ).lower()
    tokens = set(text.replace("_", "-").replace(" ", "-").split("-"))
    role = server.labels.get("role", "").lower()
    for key, _title, words in GROUPS:
        if role and any(word == role or role.startswith(word) for word in words):
            return key
    for key, _title, words in GROUPS:
        if tokens & set(words):
            return key
    return "other"


def _sensitive(server: Asset) -> bool:
    explicit = server.labels.get("sensitivity", "").lower()
    if explicit in {"high", "low", "none"}:
        return explicit == "high"
    return _group(server) in {"security", "data"} and any(
        word in (server.labels.get("role", "") + " " + server.name).lower()
        for word in ("db", "database", "postgres", "redis", "vault", "auth", "identity", "secret")
    )


def build_topology(snapshot: Snapshot) -> dict[str, Any]:
    networks = [asset for asset in snapshot.assets if asset.type == "network"]
    private_ranges = tuple(
        ipaddress.ip_network(str(item.properties["ip_range"]), strict=False)
        for item in networks
        if item.properties.get("ip_range")
    )
    network_names = {item.properties.get("id"): item.name for item in networks}
    volumes = {asset.properties.get("id"): asset for asset in snapshot.assets if asset.type == "volume"}
    container_images: dict[str, list[str]] = {}
    for asset in snapshot.assets:
        if asset.type == "container":
            container_images.setdefault(str(asset.properties.get("server")), []).append(str(asset.properties.get("image") or ""))
    servers = []
    for server in sorted(
        (asset for asset in snapshot.assets if asset.type == "server"), key=lambda item: item.name
    ):
        props = server.properties
        ingress: dict[str, list[str]] = {}
        edge_names: set[str] = set()
        mesh_names: set[str] = set()
        for rule in props.get("inbound", []) or []:
            classes = {classify_source(str(source), private_ranges) for source in rule.get("sources", [])}
            edge_names.update(filter(None, (edge_provider(str(source)) for source in rule.get("sources", []))))
            if any(is_mesh(str(source)) for source in rule.get("sources", [])):
                mesh_names.add("Tailscale/Headscale/NetBird")
            for kind in classes:
                port = _port_text(rule)
                mesh = mesh_port(rule.get("protocol"), rule.get("port_from")) if rule.get("port_from") == rule.get("port_to") else None
                if kind == "world" and mesh:
                    kind, port = "mesh", f"udp/{rule.get('port_from')} ({mesh})"
                    mesh_names.add(mesh)
                ports = ingress.setdefault(kind, [])
                if port not in ports:
                    ports.append(port)
                    ports.sort(key=_port_sort_key)
        world_ports = [port for port in ingress.get("world", []) if port != "icmp"]
        sensitive_world = [
            port
            for port in world_ports
            if port.endswith("/all")
            or any(port == f"tcp/{number}" for number in SENSITIVE_PORTS)
        ]
        exposure = (
            "critical" if sensitive_world or (props.get("public_ip") and not props.get("firewall_attached"))
            else "public" if world_ports
            else "proxied" if ingress.get("edge")
            else "private"
        )
        server_type: dict[str, Any] = props["server_type"] if isinstance(props.get("server_type"), dict) else {}
        location: dict[str, Any] = props["location"] if isinstance(props.get("location"), dict) else {}
        attached = [
            volumes[volume_id] for volume_id in props.get("volumes", []) or [] if volume_id in volumes
        ]
        servers.append(
            {
                "id": server.id,
                "name": server.name,
                "group": _group(server),
                "role": server.labels.get("role") or server.labels.get("service") or "",
                "environment": server.labels.get("environment", ""),
                "type": server_type.get("name", ""),
                "deprecated_type": server_type.get("deprecated") is True,
                "location": location.get("name", ""),
                "network_zone": location.get("network_zone", ""),
                "status": props.get("status", ""),
                "public_ip": bool(props.get("public_ip")),
                "firewall": bool(props.get("firewall_attached")),
                "networks": [
                    network_names.get(item.get("network"), str(item.get("network")))
                    for item in props.get("private_net", []) or []
                ],
                "private_ips": [
                    str(item.get("ip")) for item in props.get("private_net", []) or [] if item.get("ip")
                ],
                "volume_gb": sum(int(item.properties.get("size", 0) or 0) for item in attached),
                "backups": bool(props.get("backup_enabled")),
                "delete_protection": bool(props.get("delete_protection")),
                "sensitive": _sensitive(server),
                "ingress": ingress,
                "exposure": exposure,
                "edge_providers": sorted(edge_names),
                "mesh_providers": sorted(mesh_names),
                # A public server that accepts nothing from the Internet: admin over a mesh VPN, apps via tunnels.
                "no_public_ingress": bool(props.get("public_ip")) and bool(props.get("firewall_attached")) and not any(
                    port != "icmp" for kind in ("world", "edge", "allowlist") for port in ingress.get(kind, [])
                ),
                "tunnels": sorted({*tunnel_agents(props), *container_tunnels(container_images.get(server.id, []))}),
                "host": _host_summary(server),
                "k8s_role": (props.get("k8s") or {}).get("role"),
            }
        )
    unattached = [
        asset for asset in snapshot.assets if asset.type == "volume" and not asset.properties.get("server")
    ]
    storage_boxes = []
    for asset in snapshot.assets:
        if asset.type != "storage_box":
            continue
        box_location = asset.properties.get("location")
        box_type = asset.properties.get("storage_box_type")
        storage_boxes.append(
            {
                "name": asset.name,
                "location": box_location.get("name", "") if isinstance(box_location, dict) else str(box_location or ""),
                "type": box_type.get("name", "") if isinstance(box_type, dict) else str(box_type or ""),
            }
        )
    volumes_all = [asset for asset in snapshot.assets if asset.type == "volume"]
    stats = {
        "servers": len(servers),
        "locations": len({item["location"] for item in servers if item["location"]}),
        "internet_exposed": sum(1 for item in servers if item["exposure"] in {"public", "critical"}),
        "edge_fronted": sum(1 for item in servers if item["exposure"] == "proxied"),
        "mesh_admin": sum(
            1 for item in servers if any(port.startswith("tcp/") or port == "all" for port in item["ingress"].get("mesh", []))
        ),
        "no_public_ingress": sum(1 for item in servers if item["no_public_ingress"]),
        "tunnels": sum(1 for item in servers if item["tunnels"]),
        # Hetzner Cloud Firewalls do not filter private networks: every member reaches every other.
        "private_members": sum(1 for item in servers if item["networks"]),
        "no_firewall": sum(1 for item in servers if item["public_ip"] and not item["firewall"]),
        "volumes": len(volumes_all),
        "volume_gb": sum(int(item.properties.get("size", 0) or 0) for item in volumes_all),
        "unattached_volumes": len(unattached),
        "deprecated_types": sum(1 for item in servers if item["deprecated_type"]),
        "delete_protected": sum(1 for item in servers if item["delete_protection"]),
        "backups_enabled": sum(1 for item in servers if item["backups"]),
    }
    return {
        "networks": [
            {
                "name": item.name,
                "ip_range": item.properties.get("ip_range", ""),
                "subnets": [
                    str(subnet.get("ip_range"))
                    for subnet in item.properties.get("subnets", []) or []
                    if isinstance(subnet, dict) and subnet.get("ip_range")
                ],
                "network_zone": next(
                    (
                        str(subnet.get("network_zone"))
                        for subnet in item.properties.get("subnets", []) or []
                        if isinstance(subnet, dict) and subnet.get("network_zone")
                    ),
                    "",
                ),
            }
            for item in networks
        ],
        "servers": servers,
        "edge_providers": sorted({name for item in servers for name in item["edge_providers"]}),
        "mesh_providers": sorted({name for item in servers for name in item["mesh_providers"]}),
        "storage_boxes": storage_boxes,
        **_beyond(snapshot),
        "unattached_volumes": [asset.name for asset in unattached],
        "stats": stats,
        "collected_at": snapshot.metadata.get("collected_at"),
    }


def _host_summary(server: Asset) -> dict[str, Any] | None:
    """Host-bundle facts a diagram can show: firewall engine, Docker bypass, container count."""
    props = server.properties
    if not props.get("host_evidence"):
        return None
    firewall = props.get("host_firewall") or {}
    own = port_set(firewall.get("world_tcp_ranges"))
    bypass = sorted({item["host_port"] for item in props.get("docker_published") or []
                     if item.get("bind") in {"wildcard", "public"} and item["host_port"] not in own})
    return {
        "firewall": ("unknown" if not firewall or not firewall.get("known", True)
                     else firewall.get("engine") if firewall.get("active") else "none"),
        "docker_bypass": bypass,
        "containers": len({item.get("container") for item in props.get("docker_published") or []}),
        "password_ssh": (props.get("sshd") or {}).get("passwordauthentication") == "yes",
    }


def _beyond(snapshot: Snapshot) -> dict[str, Any]:
    """Resources outside the server grid: load balancers, Robot, vSwitch, buckets, Kubernetes, misc."""
    from .collectors.objectstorage import public_grants, public_statements

    names = {asset.id: asset.name for asset in snapshot.assets}
    of = snapshot.assets
    load_balancers = []
    for lb in (asset for asset in of if asset.type == "load_balancer"):
        targets = set()
        for target in lb.properties.get("targets") or []:
            for item in [target, *(target.get("targets") or [])]:
                server_id = (item.get("server") or {}).get("id")
                if server_id is not None:
                    targets.add(names.get(f"hcloud:server:{server_id}", str(server_id)))
        # IP targets, resolved to Cloud or Robot servers where possible, else shown as the address.
        targets |= {names.get(edge.target, edge.target) for edge in snapshot.edges
                    if edge.source == lb.id and edge.relation == "allows" and edge.target.startswith(("robot:", "endpoint:"))}
        load_balancers.append({
            "name": lb.name,
            "public": bool((lb.properties.get("public_net") or {}).get("enabled", True)),
            "services": [f"{item.get('protocol')} {item.get('listen_port')}→{item.get('destination_port')}" for item in lb.properties.get("services") or []],
            "targets": sorted(targets),
        })
    robot = [
        {"name": asset.name, "product": asset.properties.get("product"), "dc": asset.properties.get("dc"),
         "firewall": (asset.properties.get("robot_firewall") or {}).get("status") or "absent",
         "filter_ipv6": (asset.properties.get("robot_firewall") or {}).get("filter_ipv6")}
        for asset in of if asset.type == "robot_server"
    ]
    vswitches = [
        {"name": asset.name, "vlan": asset.properties.get("vlan"),
         "members": [names.get(f"robot:server:{number}", str(number)) for number in asset.properties.get("servers") or []],
         "cloud_networks": [names.get(f"hcloud:network:{item.get('id')}", str(item.get("id"))) for item in asset.properties.get("cloud_network") or []]}
        for asset in of if asset.type == "vswitch"
    ]
    buckets = [
        {"name": asset.name, "location": asset.properties.get("location"),
         "public": bool(public_grants(asset.properties) or public_statements(asset.properties)),
         "versioning": asset.properties.get("versioning") == "Enabled"}
        for asset in of if asset.type == "bucket"
    ]
    k8s = None
    cluster = next((asset for asset in of if asset.type == "k8s_cluster"), None)
    if cluster:
        k8s = {
            "name": cluster.name,
            "nodes": sorted(asset.name for asset in of if asset.type == "server" and asset.properties.get("k8s")),
            "risky_workloads": sum(1 for asset in of if asset.type == "k8s_workload" and not asset.properties.get("system")),
            "system_workloads": sum(1 for asset in of if asset.type == "k8s_workload" and asset.properties.get("system")),
            "node_port_services": sum(1 for asset in of if asset.type == "k8s_service"),
            "integrations": cluster.properties.get("integrations") or [],
        }
    misc = {kind: sum(1 for asset in of if asset.type == kind)
            for kind in ("floating_ip", "certificate", "zone", "placement_group")}
    return {"load_balancers": load_balancers, "robot_servers": robot, "vswitches": vswitches, "buckets": buckets,
            "kubernetes": k8s, "misc": {key: value for key, value in misc.items() if value},
            "projects": [item["name"] for item in snapshot.metadata.get("projects") or []]}


def _group_title(key: str) -> str:
    return next((title for group, title, _words in GROUPS if group == key), "Other")


def _mermaid_text(value: object) -> str:
    """Entity-encode label text so names cannot close a Mermaid label or inject markup or links."""
    text = escape(" ".join(str(value).split()), quote=True)
    return text.replace("[", "&#91;").replace("]", "&#93;").replace("|", "&#124;").replace("(", "&#40;").replace(")", "&#41;")


def _node_id(name: str) -> str:
    return "n_" + "".join(char if char.isalnum() else "_" for char in name)


def render_mermaid(topology: dict[str, Any]) -> str:
    lines = ["flowchart LR"]
    sources_used = sorted(
        {kind for server in topology["servers"] for kind in server["ingress"] if kind != "private"}
    )
    for kind in sources_used:
        shape = ("((", "))") if kind == "world" else ("([", "])")
        label = f"Edge proxy: {', '.join(topology.get('edge_providers') or ['CDN'])}" if kind == "edge" else SOURCE_LABELS[kind]
        lines.append(f'  src_{kind}{shape[0]}"{_mermaid_text(label)}"{shape[1]}')
    network_title = ", ".join(f"{net['name']} {net['ip_range']}" for net in topology["networks"]) or "Private network"
    sections = [
        ("net", network_title, [item for item in topology["servers"] if item["networks"]]),
        ("nonet", "No private network", [item for item in topology["servers"] if not item["networks"]]),
    ]
    for section_id, section_title, members in sections:
        if not members:
            continue
        lines.append(f'  subgraph {section_id}["{_mermaid_text(section_title)}"]')
        groups: dict[str, list[dict[str, Any]]] = {}
        for server in members:
            groups.setdefault(server["group"], []).append(server)
        for key in [group for group, _t, _w in GROUPS] + ["other"]:
            if key not in groups:
                continue
            lines.append(f'    subgraph {section_id}_{key}["{_group_title(key)}"]')
            lines.append("      direction TB")
            for server in groups[key]:
                detail = " · ".join(item for item in (server["role"], server["type"], server["location"]) if item)
                lines.append(f'      {_node_id(server["name"])}["{_mermaid_text(server["name"])}<br/><small>{_mermaid_text(detail)}</small>"]')
            lines.append("    end")
        lines.append("  end")
    for server in topology["servers"]:
        for kind, ports in server["ingress"].items():
            if kind in {"private", "mesh"}:
                continue
            visible = [port for port in ports if port != "icmp"]
            if not visible:
                continue
            arrow = "==>" if kind == "world" else "-->"
            lines.append(f'  src_{kind} {arrow}|"{", ".join(visible)}"| {_node_id(server["name"])}')
    if "mesh" in sources_used:
        for section_id, _title, members in sections:
            if any("mesh" in item["ingress"] for item in members):
                lines.append(f'  src_mesh -.->|"admin & VPN"| {section_id}')
    styles = {
        "critical": "fill:#4a1717,stroke:#f87171,color:#fee2e2",
        "public": "fill:#43300f,stroke:#fbbf24,color:#fef3c7",
        "proxied": "fill:#0f3a2e,stroke:#34d399,color:#d1fae5",
        "private": "fill:#13233a,stroke:#60a5fa,color:#dbeafe",
    }
    for exposure, style in styles.items():
        members = [_node_id(item["name"]) for item in topology["servers"] if item["exposure"] == exposure]
        if members:
            lines.append(f"  classDef {exposure} {style}")
            lines.append(f"  class {','.join(members)} {exposure}")
    return "\n".join(lines)


def render_topology_markdown(topology: dict[str, Any]) -> str:
    counts: dict[str, int] = {}
    for server in topology["servers"]:
        counts[server["exposure"]] = counts.get(server["exposure"], 0) + 1
    lines = [
        "# Hetzner Network Map",
        "",
        f"Collected at: {topology.get('collected_at') or 'unknown'} · servers: {len(topology['servers'])} · "
        + " · ".join(f"{key}: {value}" for key, value in sorted(counts.items())),
        "",
        "```mermaid",
        render_mermaid(topology),
        "```",
        "",
        "Exposure: **critical** = sensitive port or all ports open to any address, or no cloud firewall; "
        "**public** = other ports open to any address; **proxied** = reachable only through an edge proxy/CDN "
        f"({', '.join(topology.get('edge_providers') or []) or 'none seen'}); "
        "**private** = no public ingress except a mesh VPN's UDP port (Tailscale, WireGuard/NetBird, ZeroTier). "
        "Hetzner Cloud Firewalls do not filter private networks, so members of one network reach each other on every port.",
        "",
        "| Server | Group | Type | Exposure | Public ingress | Private / admin ingress |",
        "|---|---|---|---|---|---|",
    ]
    for server in topology["servers"]:
        public = "; ".join(
            f"{SOURCE_LABELS[kind]}: {', '.join(port for port in ports if port != 'icmp')}"
            for kind, ports in server["ingress"].items()
            if kind in {"world", "edge", "allowlist"} and any(port != "icmp" for port in ports)
        ) or ("none (ICMP only)" if "icmp" in server["ingress"].get("world", []) else "none")
        private = "; ".join(
            [f"{SOURCE_LABELS['mesh']}: {', '.join(server['ingress']['mesh'])}"]
            if server["ingress"].get("mesh")
            else []
        )
        if server["networks"]:
            private = "; ".join(
                part for part in (private, f"{', '.join(server['networks'])}: all ports (not filtered by cloud firewalls)") if part
            )
        private = private or "none"
        server_type = server["type"] + (" (deprecated)" if server["deprecated_type"] else "")
        lines.append(
            f"| {md(server['name'])} | {_group_title(server['group'])} | {md(server_type)} | {server['exposure']} | {md(public)} | {md(private)} |"
        )
    if topology["unattached_volumes"]:
        lines.extend(["", "Unattached volumes: " + ", ".join(md(name) for name in topology["unattached_volumes"])])
    lines.extend(["", "Public IP addresses are intentionally omitted. The map shows provider firewall intent, not host or application controls."])
    return "\n".join(lines)
