"""Fetch the IP ranges edge providers publish and regenerate src/hetzner_security/provider_ranges.py.

Run: `uv run python scripts/update_provider_ranges.py` (network access needed). `--check` compares
with the bundled lists and exits 1 when any provider changed, without writing anything.
Providers whose list cannot be fetched keep their previous ranges and date.
"""

from __future__ import annotations

import datetime as dt
import ipaddress
import json
import sys
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any

OUTPUT = Path(__file__).resolve().parent.parent / "src" / "hetzner_security" / "provider_ranges.py"


def _get(url: str, data: bytes | None = None) -> Any:
    request = urllib.request.Request(  # noqa: S310 -- fixed HTTPS URLs below
        url, data=data, headers={"User-Agent": "hetzner-audit/provider-ranges", "Accept": "application/json"},
        method="POST" if data else "GET",
    )
    with urllib.request.urlopen(request, timeout=30) as response:  # noqa: S310
        return json.loads(response.read())


def cloudflare() -> list[str]:
    result = _get("https://api.cloudflare.com/client/v4/ips")["result"]
    return [*result["ipv4_cidrs"], *result["ipv6_cidrs"]]


def fastly() -> list[str]:
    data = _get("https://api.fastly.com/public-ip-list")
    return [*data["addresses"], *data.get("ipv6_addresses", [])]


def bunny() -> list[str]:
    v4 = _get("https://bunnycdn.com/api/system/edgeserverlist")
    v6 = _get("https://bunnycdn.com/api/system/edgeserverlist/IPv6")
    return [*v4, *v6]


def cloudfront() -> list[str]:
    data = _get("https://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips")
    return [*data["CLOUDFRONT_GLOBAL_IP_LIST"], *data["CLOUDFRONT_REGIONAL_EDGE_IP_LIST"]]


def gcore() -> list[str]:
    data = _get("https://api.gcore.com/cdn/public-ip-list")
    return [*data["addresses"], *data.get("addresses_v6", [])]


def imperva() -> list[str]:
    data = _get("https://my.imperva.com/api/integration/v1/ips", urllib.parse.urlencode({"resp_format": "json"}).encode())
    return [*data["ipRanges"], *data.get("ipv6Ranges", [])]


FETCHERS = {
    "cloudflare": ("Cloudflare", "https://www.cloudflare.com/ips/", cloudflare),
    "fastly": ("Fastly", "https://api.fastly.com/public-ip-list", fastly),
    "bunny": ("Bunny CDN", "https://bunny.net/api/system/edgeserverlist", bunny),
    "cloudfront": ("AWS CloudFront", "https://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips", cloudfront),
    "gcore": ("Gcore CDN", "https://api.gcore.com/cdn/public-ip-list", gcore),
    "imperva": ("Imperva", "https://my.imperva.com/api/integration/v1/ips", imperva),
}


def _normalize(values: list[str]) -> list[str]:
    networks = {ipaddress.ip_network(value.strip(), strict=False) for value in values if value.strip()}
    collapsed = [*ipaddress.collapse_addresses(n for n in networks if n.version == 4),
                 *ipaddress.collapse_addresses(n for n in networks if n.version == 6)]
    return [str(network) for network in collapsed]


def _current() -> dict[str, dict[str, Any]]:
    if not OUTPUT.exists():
        return {}
    namespace: dict[str, Any] = {}
    exec(compile(OUTPUT.read_text(), str(OUTPUT), "exec"), namespace)  # noqa: S102 -- our own generated file
    return dict(namespace["EDGE_RANGES"])


def main() -> int:
    check = "--check" in sys.argv
    today = dt.date.today().isoformat()
    current = _current()
    updated: dict[str, dict[str, Any]] = {}
    changed = []
    for key, (name, source, fetch) in FETCHERS.items():
        try:
            ranges = _normalize(fetch())
        except Exception as exc:  # noqa: BLE001 -- keep the previous list and say so
            print(f"{name}: fetch failed ({exc}); keeping the bundled list", file=sys.stderr)
            if key in current:
                updated[key] = current[key]
            continue
        previous = current.get(key, {})
        same = sorted(previous.get("ranges", [])) == sorted(ranges)
        if not same:
            changed.append(name)
        updated[key] = {"name": name, "source": source, "as_of": previous.get("as_of") if same else today, "ranges": ranges}
        print(f"{name}: {len(ranges)} ranges{'' if same else ' (changed)'}")
    if check:
        print("changed: " + (", ".join(changed) or "none"))
        return 1 if changed else 0
    lines = [
        '"""Edge-provider IP ranges, generated by scripts/update_provider_ranges.py. Do not edit by hand.',
        "",
        "Each list is what the provider published on its `as_of` date (collapsed CIDRs).",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        "EDGE_RANGES: dict[str, dict[str, Any]] = {",
    ]
    for key, entry in updated.items():
        lines.append(f"    {key!r}: {{")
        lines.append(f"        \"name\": {entry['name']!r},")
        lines.append(f"        \"source\": {entry['source']!r},")
        lines.append(f"        \"as_of\": {entry['as_of']!r},")
        lines.append("        \"ranges\": (")
        lines.extend(f"            {value!r}," for value in entry["ranges"])
        lines.append("        ),")
        lines.append("    },")
    lines.append("}")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
